service:
  name: mcf-node

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  
functions:
  test:
    handler: src/handlers/test.handler
    events:
      - http:
          method: GET
          path: /test
