service: mcf-node

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    MCFNODE_BUCKET_NAME: ${self:custom.McfnodeBucket.name}
  iamRoleStatements:
    - ${file(iam/McfnodeBucketIAM.yml):McfnodeBucketIAM}
  
resources:
  Resources:
    McfnodeBucket: ${file(resources/McfnodeBucket.yml):McfnodeBucket}
    McfnodeBucketPolicy: ${file(resources/McfnodeBucket.yml):McfnodeBucketPolicy}

functions:
  getjson:
    handler: src/handlers/getjson.handler
    events:
      - http:
          method: GET
          path: /getjson
custom:
  McfnodeBucket:
    name: mcfnode-bucket-${self:provider.stage}
  bundle:
    linting: false